---
# Source: cassandra-operator/templates/db_v1alpha1_cassandracluster_crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandraclusters.db.orange.com
  namespace: cassandra
  labels:
    app: cassandra-operator
    chart: cassandra-operator-0.3.3
    heritage: Tiller
    release: casskop
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: db.orange.com
  names:
    kind: CassandraCluster
    listKind: CassandraClusterList
    plural: cassandraclusters
    singular: cassandracluster
  scope: Namespaced
  version: v1alpha1
