---
# Source: cassandra-operator/templates/rolebinding.yaml

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: cassandra-operator
    chart: cassandra-operator-0.3.3
    heritage: Tiller
    release: casskop
  name: cassandra-operator
  namespace: cassandra
subjects:
- kind: ServiceAccount
  name: cassandra-operator
roleRef:
  kind: Role
  name: cassandra-operator
  apiGroup: rbac.authorization.k8s.io
